{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "‼️‼️‼️Bienvenidos a Juego Piedra💎, Papel🧻 y Tijeras✂‼️‼️‼️\n",
      "📒 Reglas del Juego : \n",
      "\n",
      " - Escoge entre  \"Piedra\"💎, \"Papel\"🧻 o \"Tijera\"✂. \n",
      " - Piedra vence a Tijera, Tijera vence a Papel y Papel vence a Piedra \n",
      " - ¡¡El ganador será el que llegue antes a 3 puntos!! \n",
      "\n",
      "\n",
      "💪😎 EMPECEMOS \n",
      "\n",
      "\n",
      "Jugador ha elegido Piedra💎\n",
      "La máquina ha elegido Tijera\n",
      "¡Has acertado! 😀 Vais Jugador 1 y Máquina 0\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Papel🧻\n",
      "La máquina ha elegido Piedra\n",
      "¡Has acertado! 😀 Vais Jugador 2 y Máquina 0\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Tijera✂\n",
      "La máquina ha elegido Piedra\n",
      "!Qué pena¡ 😔 Sigue jugando. Vais Jugador 2 y Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Papel🧻\n",
      "La máquina ha elegido Papel\n",
      "Empate 🤷‍♀️. Vais Jugador 2 y Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Papel🧻\n",
      "La máquina ha elegido Papel\n",
      "Empate 🤷‍♀️. Vais Jugador 2 y Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Papel🧻\n",
      "La máquina ha elegido Papel\n",
      "Empate 🤷‍♀️. Vais Jugador 2 y Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "Jugador ha elegido Piedra💎\n",
      "La máquina ha elegido Tijera\n",
      "¡Has acertado! 😀 Vais Jugador 3 y Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "El total de puntos es: Jugador 3 / Máquina 1\n",
      "➖➖➖➖➖➖➖➖➖➖➖➖➖\n",
      "\n",
      "\n",
      "🎉🎉🎉¡¡¡GANASTE!!!🎉🎉🎉\n",
      "\n",
      "\n",
      "¡Gracias por jugar!\n",
      " (\\__/)\n",
      " (>’.’<)\n",
      " («)_(«) \n",
      "\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "print(\"‼️‼️‼️Bienvenidos a Juego Piedra💎, Papel🧻 y Tijeras✂‼️‼️‼️\")\n",
    "\n",
    "print(f'📒 Reglas del Juego : \\n\\n - Escoge entre  \"Piedra\"💎, \"Papel\"🧻 o \"Tijera\"✂. \\n - Piedra vence a Tijera, Tijera vence a Papel y Papel vence a Piedra \\n - ¡¡El ganador será el que llegue antes a 3 puntos!! \\n\\n')\n",
    "print('💪😎 EMPECEMOS \\n\\n')\n",
    "\n",
    "puntos = 0\n",
    "puntos_maquina = 0\n",
    "lista = [\"Piedra\", \"Papel\", \"Tijera\"]\n",
    "\n",
    "while puntos <= 3 or puntos_maquina <= 3:\n",
    "\n",
    "    jugador = input(\"Elige Piedra💎, papel🧻 o tijera✂\").capitalize()\n",
    "    maquina = random.choice(lista)\n",
    "\n",
    "    if jugador == \"Piedra\":\n",
    "        print(f\"Jugador ha elegido {jugador}💎\")\n",
    "        print(f\"La máquina ha elegido {maquina}\")\n",
    "\n",
    "        if maquina == jugador:\n",
    "            puntos += 0\n",
    "            puntos_maquina += 0\n",
    "            print(f\"Empate 🤷‍♀️. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Papel\" and jugador == \"Piedra\":\n",
    "            puntos += 0\n",
    "            puntos_maquina += 1\n",
    "            print(f\"!Qué pena¡ 😔 Sigue jugando. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Tijera\" and jugador == \"Piedra\":\n",
    "            puntos += 1\n",
    "            puntos_maquina += 0\n",
    "            print(f\"¡Has acertado! 😀 Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "    elif jugador == \"Papel\":\n",
    "        print(f\"Jugador ha elegido {jugador}🧻\")\n",
    "        print(f\"La máquina ha elegido {maquina}\") \n",
    "\n",
    "        if maquina == jugador:\n",
    "            puntos += 0\n",
    "            puntos_maquina += 0\n",
    "            print(f\"Empate 🤷‍♀️. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Piedra\" and jugador == \"Papel\":\n",
    "            puntos += 1\n",
    "            puntos_maquina += 0\n",
    "            print(f\"¡Has acertado! 😀 Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Tijera\" and jugador == \"Papel\":\n",
    "            puntos += 0\n",
    "            puntos_maquina += 1\n",
    "            print(f\"!Qué pena¡ 😔 Sigue jugando. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "    elif  jugador == \"Tijera\":\n",
    "        print(f\"Jugador ha elegido {jugador}✂\")\n",
    "        print(f\"La máquina ha elegido {maquina}\") \n",
    "\n",
    "        if maquina == jugador:\n",
    "            puntos += 0\n",
    "            puntos_maquina += 0\n",
    "            print(f\"Empate 🤷‍♀️. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Papel\" and jugador == \"Tijera\":\n",
    "            puntos += 1\n",
    "            puntos_maquina += 0\n",
    "            print(f\"¡Has acertado! 😀 Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "        elif maquina == \"Piedra\" and jugador == \"Tijera\":\n",
    "            puntos += 0\n",
    "            puntos_maquina += 1\n",
    "            print(f\"!Qué pena¡ 😔 Sigue jugando. Vais Jugador {puntos} y Máquina {puntos_maquina}\")\n",
    "            print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "            print(\"\\n\")\n",
    "\n",
    "    else:\n",
    "        print(\"No has elegido un valor correcto ❌\")\n",
    "        print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "        print(\"\\n\")\n",
    "\n",
    "    if puntos == 3 or puntos_maquina == 3:\n",
    "        print(f\"El total de puntos es: Jugador {puntos} / Máquina {puntos_maquina}\")\n",
    "        print(\"➖➖➖➖➖➖➖➖➖➖➖➖➖\")\n",
    "        print(\"\\n\")\n",
    "        if puntos == 3:\n",
    "            print(\"🎉🎉🎉¡¡¡GANASTE!!!🎉🎉🎉\")\n",
    "            print(\"\\n\")\n",
    "            break\n",
    "        else:\n",
    "            print(\"\\n💀💀💀¡¡¡PERDISTE!!!💀💀💀\")\n",
    "            print(\"\\n\")\n",
    "            break\n",
    "   \n",
    "Gato = \"(\\__/)\"\"\\n\"\" (>’.’<)\"\"\\n\"\" («)_(«)\"\n",
    "print(f\"¡Gracias por jugar!\\n {Gato} \\n\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
